//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IZWebFileManagerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IZWebFileManagerResource() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.IZWebFileManagerResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Arrange Icons By.
        /// </summary>
        internal static string Arrange_Icons_By {
            get {
                return ResourceManager.GetString("Arrange_Icons_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Cannot Complete Operation..
        /// </summary>
        internal static string CannotCompleteOperation {
            get {
                return ResourceManager.GetString("CannotCompleteOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Cannot find file, Make sure the path is correct..
        /// </summary>
        internal static string CannotFindFile {
            get {
                return ResourceManager.GetString("CannotFindFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Cannot rename file: A file with the name you specified already exists. Specify a different file name..
        /// </summary>
        internal static string CannotRenameFile {
            get {
                return ResourceManager.GetString("CannotRenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a New.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a New Folder.
        /// </summary>
        internal static string Create_New_Folder {
            get {
                return ResourceManager.GetString("Create_New_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Date Modified.
        /// </summary>
        internal static string Date_Modified {
            get {
                return ResourceManager.GetString("Date_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Are you sure you want to delete selected items?.
        /// </summary>
        internal static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a The destination folder is a subfolder of the source folder..
        /// </summary>
        internal static string DestinationFolderIsSubfolder {
            get {
                return ResourceManager.GetString("DestinationFolderIsSubfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a File Folder.
        /// </summary>
        internal static string File_Folder {
            get {
                return ResourceManager.GetString("File_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Folder Path.
        /// </summary>
        internal static string Folder_Path {
            get {
                return ResourceManager.GetString("Folder_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Icons.
        /// </summary>
        internal static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Insufficient user privileges to complete the operation.
        /// </summary>
        internal static string Insufficient_privileges {
            get {
                return ResourceManager.GetString("Insufficient_privileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Move.
        /// </summary>
        internal static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a You must type a file name..
        /// </summary>
        internal static string MustTypeFileName {
            get {
                return ResourceManager.GetString("MustTypeFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Folder.
        /// </summary>
        internal static string New_Folder {
            get {
                return ResourceManager.GetString("New_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a New Folder.
        /// </summary>
        internal static string New_Folder_Name {
            get {
                return ResourceManager.GetString("New_Folder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a A file name cannot contain any of the following characters: \/:*?&quot;&lt;&gt;|.
        /// </summary>
        internal static string NotAllowedCharacters {
            get {
                return ResourceManager.GetString("NotAllowedCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a DoubleClick to open a folder. DoubleClick to download a file..
        /// </summary>
        internal static string No_Command_Help {
            get {
                return ResourceManager.GetString("No_Command_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Rename.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Files.
        /// </summary>
        internal static string Root_File {
            get {
                return ResourceManager.GetString("Root_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Flash Movies.
        /// </summary>
        internal static string Root_Flash {
            get {
                return ResourceManager.GetString("Root_Flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Images.
        /// </summary>
        internal static string Root_Image {
            get {
                return ResourceManager.GetString("Root_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Media.
        /// </summary>
        internal static string Root_Media {
            get {
                return ResourceManager.GetString("Root_Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Search.
        /// </summary>
        internal static string SearchWatermark {
            get {
                return ResourceManager.GetString("SearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select destination directory.
        /// </summary>
        internal static string SelectDestination {
            get {
                return ResourceManager.GetString("SelectDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Thumbnails.
        /// </summary>
        internal static string Thumbnails {
            get {
                return ResourceManager.GetString("Thumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Up.
        /// </summary>
        internal static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Upload Another File.
        /// </summary>
        internal static string Upload_Another_File {
            get {
                return ResourceManager.GetString("Upload_Another_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Or drag &apos;nd drop one or more files on the above area.
        /// </summary>
        internal static string Upload_dnd {
            get {
                return ResourceManager.GetString("Upload_dnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a File exceeds maximum size allowed ({0} mb).
        /// </summary>
        internal static string Upload_Error_1 {
            get {
                return ResourceManager.GetString("Upload_Error_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a File type not allowed or not supported..
        /// </summary>
        internal static string Upload_Error_2 {
            get {
                return ResourceManager.GetString("Upload_Error_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a User does not have sufficient privileges..
        /// </summary>
        internal static string Upload_Error_3 {
            get {
                return ResourceManager.GetString("Upload_Error_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Upload File.
        /// </summary>
        internal static string Upload_File {
            get {
                return ResourceManager.GetString("Upload_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Click here to upload a file.
        /// </summary>
        internal static string Upload_File_click {
            get {
                return ResourceManager.GetString("Upload_File_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Remove.
        /// </summary>
        internal static string Upload_File_Remove {
            get {
                return ResourceManager.GetString("Upload_File_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a File type not allowed or not supported..
        /// </summary>
        internal static string Upload_not_allowed {
            get {
                return ResourceManager.GetString("Upload_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a File &quot;{0}&quot; was successfully uploaded.
        /// </summary>
        internal static string Upload_success {
            get {
                return ResourceManager.GetString("Upload_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a File view.
        /// </summary>
        internal static string View_file {
            get {
                return ResourceManager.GetString("View_file", resourceCulture);
            }
        }
    }
}
